Update openshift.yml

diff --git a/.github/workflows/openshift.yml b/.github/workflows/openshift.yml
--- a/.github/workflows/openshift.yml
+++ b/.github/workflows/openshift.yml
@@ -1,70 +1,80 @@
-name: OpenShift
+name: OpenShiftDeployment
 
-env: 
-  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
-  REGISTRY_USER: ${{ github.actor }}
-  REGISTRY_PASSWORD: ${{ github.token }}
-  APP_NAME: sweng_test
-  IMAGE_TAGS: latest ${{ github.sha }}
-
+env:
   OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
   OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
-  OPENSHIFT_NAMESPACE: "%PROJECT%"
-
+  # 🖊️ EDIT to set the kube context's namespace after login. Leave blank to use your user's default namespace.
+  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_PROJECT }}
+  # 🖊️ EDIT to set a name for your OpenShift app, or a default one will be generated below.
+  APP_NAME: "sweng_test"
   APP_PORT: "8080"
-
+  
 on:
-  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
-  push: 
-    branches: [ main ]
+  workflow_run:
+    workflows: ["Publish to Quay.io"]
+    types:
+      - completed
+jobs:   
+  openshift-deploy:
+      name: Deploy to OpenShift
+      # ubuntu-20.04 can also be used.
+      runs-on: ubuntu-18.04
 
-jobs:
-  build-and-push: 
-    name: Build and push to github container registry
-    runs-on: ubuntu-18.04
-    environment: development
-
-    outputs:
+      outputs:
         ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
         SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+ 
+      steps:
+      - name: Install oc
+        uses: redhat-actions/openshift-tools-installer@v1
+        with:
+          oc: 4
+ 
+      # https://github.com/redhat-actions/oc-login#readme
+      - name: Log in to OpenShift
+        uses: redhat-actions/oc-login@v1
+        with:
+          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
+          insecure_skip_tls_verify: true
+          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
 
-    steps:
-    - name: Checkout
-      id: checkout
-      uses: actions/checkout@v2
+      - name: Create and expose app
+        id: deploy-and-expose
+        uses: redhat-actions/oc-new-app@v1
+        with:
+          app_name: ${{ env.APP_NAME }}
+          image: quay.io/sweng_moeto/sweng_test
+          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+          port: ${{ env.APP_PORT }}
+          
+#       - name: Set environment
+#         run: |
+#           oc set env deployment.apps/kanbanbackend MONGODB_URL=${{ secrets.MONGODB_URL }} PORT=${{ secrets.PORT }} MONGODB_PORT=${{ secrets.MONGODB_PORT }}
+      
+      #- name: Obtain a self signed certificate
+        #run: |
+          #openssl genrsa -out key-prod.key
+          #openssl req -new -key key-prod.key -out csr-prod.csr -subj "/CN=${{ secrets.DOMAIN_WILDCARD }}"
+          #openssl x509 -req -in csr-prod.csr -signkey key-prod.key -out crt-prod.crt
+          
+      #- name: Delete Default Unsecure Route
+        #run: |
+          #oc delete route kanbanbackend
+          
+      #- name: Create new edge route using self-signed certificate
+        #run: |
+          #oc create route edge --service kanbanbackend --hostname ${{ secrets.HOSTNAME }} --key key-prod.key --cert crt-prod.crt
 
-   # https://github.com/redhat-actions/s2i-build#readme
-    - name: S2I Build 
-      id: build_image
-      uses: redhat-actions/s2i-build@v2
-      with:
-        path_context: '.'
-        builder_image: 'registry.access.redhat.com/ubi8/openjdk-11'
-        image: ${{ env.APP_NAME }}
-        tags: ${{ env.IMAGE_TAGS }}
-
-    # https://github.com/redhat-actions/push-to-registry#readme
-    - name: Push to Registry 
-      id: push-to-registry
-      uses: redhat-actions/push-to-registry@v2
-      with:
-        image: ${{ steps.build_image.outputs.image }}
-        tags: ${{ steps.build_image.outputs.tags }}
-        registry: ${{ env.IMAGE_REGISTRY }}
-        username: ${{ env.REGISTRY_USER }}
-        password: ${{ env.REGISTRY_PASSWORD }}
-
-    # The path the image was pushed to is now stored in ${{ steps.push-to-registry.outputs.registry-path }}
-
-    # https://github.com/redhat-actions/oc-login#readme
-    - name: Log in to OpenShift 
-      uses: redhat-actions/oc-login@v1
-      with:
-        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
-        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
-        insecure_skip_tls_verify: true
-        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
-
-    # Run a script to create a new app or update the current one with the previously pushed container image
-    - run: | 
-         "${GITHUB_WORKSPACE}/.github/script.sh" ${{ env.APP_NAME }} ${{ env.IMAGE_REGISTRY }}/${{ steps.build_image.outputs.image }}:${{ github.sha }} ${{ env.OPENSHIFT_NAMESPACE }}
+      - name: Print application URL
+        env:
+          ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+          SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+        run: |
+          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+          echo
+          echo "======================== Your application is available at: ========================"
+          echo ${{ env.ROUTE }}
+          echo "==================================================================================="
+          echo
+          echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
